import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-sidebaropen="true"
        className={`${geistSans.variable} ${geistMono.variable} dark flex bg-card p-3 antialiased`}
      >
        <Sidebar />
        <div
          className="flex w-1 flex-1 flex-col rounded-xl bg-background [&>*]:mx-auto [&>*]:h-1 [&>*]:w-full [&>*]:max-w-[1920px] [&>*]:flex-1 [&>*]:overflow-auto"
          style={{
            backgroundImage:
              "linear-gradient(to bottom right, #000000ff , #0000007f), url('/images/bg.jpg')",
            backgroundSize: "100% 100%, cover",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
